.Dd July 22, 2016
.Dt MCOM 1
.Os
.Sh NAME
.Nm mcom ,
.Nm mrep
.Nd compose new, reply to, and send mail
.Sh SYNOPSIS
.Nm mcom
.Op Ar recipient
.Nm mrep
.Ar msg
.Sh DESCRIPTION
.Nm mcom
creates a new draft mail and runs an editor.
After editing, a loop is started where the user can re-edit, send or
cancel the mail.
.Pp
.Nm mrep
behaves like
.Nm mcom
but fills the draft such that the mail will be a reply to the message
.Ar msg .
See
.Xr mmsg 7
for the message argument syntax.
.Sh MENU COMMANDS
.Bl -tag -width 2n
.It Ic s
Send the mail.
The MIME version will be used when one has been created.
.It Ic c
Cancel sending and quit
.Nm
after displaying the file name of the draft.
.It Ic m
Run
.Xr mmime 1
on the draft, and show the result of
.Ic mshow -t .
.It Ic e
Re-run the editor on the draft.
.It Ic d
Delete the draft and quit.
.El
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev EDITOR
Editor used to compose mail.
.It Ev MBLAZE
Directory containing mblaze configuration.
(Default:
.Pa $HOME/.mblaze )
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa snd.*
Draft messages (kept in current directory)
.It Pa ${MBLAZE:-$HOME/.mblaze}/headers
Default headers for each mail.
(Put your
.Sq Li From\&:
line there.)
.It Pa ${MBLAZE:-$HOME/.mblaze}/signature || ~/.signature
Default signature.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr mmime 1 ,
.Xr mmsg 7
.Sh AUTHORS
.An Christian Neukirchen Aq Mt chneukirchen@gmail.com
.Sh LICENSE
.Nm
is in the public domain.
.Pp
To the extent possible under law,
the creator of this work
has waived all copyright and related or
neighboring rights to this work.
.Pp
.Lk http://creativecommons.org/publicdomain/zero/1.0/
