.Dd February 4, 2021
.Dt MDELIVER 1
.Os
.Sh NAME
.Nm mdeliver
.Nd deliver messages or import mbox file
.Sh SYNOPSIS
.Nm
.Op Fl c
.Op Fl v
.Op Fl X Ar flags
.Ar dir
<
.Ar message
.Nm
.Fl M
.Op Fl c
.Op Fl v
.Op Fl X Ar flags
.Ar dir
<
.Ar mbox
.Sh DESCRIPTION
.Nm
adds a message given on the standard input
as a new message in the maildir
.Ar dir .
.Pp
When
.Fl M
is used,
.Nm
will regard the standard input as
an MBOXRD mailbox, split it on
.Dq Li "From "
and deliver each message,
decoding it according to the MBOXRD convention.
In this case,
.Nm
will set the mtime according to the value of
.Sq Li Date\&:
and the maildir flags according to the value of
.Sq Li Status\&:
or
.Sq Li X-Status\&: .
.Pp
The messages are delivered in a reliable way and use the default
.Xr umask 2 .
.Pp
Please note that no syntactical checks are performed
on the messages.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl M
Deliver each message of an mbox.
.It Fl c
Deliver messages into
.Pa cur/ ,
not
.Pa new/
(the default).
.It Fl v
Print each new message filename after delivery.
.It Fl X Ar flg
Override the flags of the new message file to be
.Ar flg .
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr mexport 1 ,
.Xr mrefile 1 ,
.Xr maildir 5 ,
.Xr mbox 5
.Pp
.Lk http://www.digitalpreservation.gov/formats/fdd/fdd000385.shtml "MBOXRD Email Format"
.Pp
.Lk https://cr.yp.to/proto/maildir.html "Using maildir format"
.Sh AUTHORS
.An Leah Neukirchen Aq Mt leah@vuxu.org
.Sh LICENSE
.Nm
is in the public domain.
.Pp
To the extent possible under law,
the creator of this work
has waived all copyright and related or
neighboring rights to this work.
.Pp
.Lk http://creativecommons.org/publicdomain/zero/1.0/
