.Dd August 17, 2016
.Dt MHDR 1
.Os
.Sh NAME
.Nm mhdr
.Nd show mail headers
.Sh SYNOPSIS
.Nm
.Op Fl h Ar header
.Op Fl d
.Op Fl H
.Op Fl M
.Op Fl A | Fl D
.Op Ar msgs\ ...
.Sh DESCRIPTION
.Nm
prints the mail headers of the given
.Ar msgs .
See
.Xr mmsg 7
for the message argument syntax.
.Pp
If no
.Ar msgs
are passed,
.Nm
will default to the current message.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h Ar header
Only print the values of the headers in the colon-separated list
.Ar header .
.It Fl d
Decode the headers according to RFC 2047.
.It Fl H
Prefix all output lines with the filename of the message, separated
by a tab.
.It Fl M
Search for all occurrences of the headers
(default: only the first).
.It Fl A
Scan for RFC 5322 addresses in the headers and print them line by line.
.It Fl D
Assume header contains RFC 5322 date and print as Unix timestamp.
.El
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success,
1 when no header was printed,
and >1 if an error occurs.
.Sh SEE ALSO
.Xr mmsg 7
.Rs
.%A N. Freed
.%A N. Borenstein
.%B MIME (Multipurpose Internet Mail Extensions) Part Three: Message Header Extensions for Non-ASCII Text
.%R RFC 2047
.%D November 1996
.Re
.Rs
.%A P. Resnick (ed.)
.%B Internet Message Format
.%R RFC 5322
.%D October 2008
.Re
.Sh AUTHORS
.An Leah Neukirchen Aq Mt leah@vuxu.org
.Sh LICENSE
.Nm
is in the public domain.
.Pp
To the extent possible under law,
the creator of this work
has waived all copyright and related or
neighboring rights to this work.
.Pp
.Lk http://creativecommons.org/publicdomain/zero/1.0/
