.Dd July 22, 2016
.Dt MINC 1
.Os
.Sh NAME
.Nm minc
.Nd incorporate new messages
.Sh SYNOPSIS
.Nm
.Op Fl q
.Ar dirs\ ...
.Sh DESCRIPTION
.Nm
incorporates new messages in the maildir folders
.Ar dirs
by moving them from
.Pa new
to
.Pa cur ,
and adjusting the filenames.
If used non-interactively with no specified folders,
.Nm
reads directory names from the standard input.
.Pp
By default, the new filenames are printed,
separated by newlines.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl q
Quiet: don't print new filenames.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Lk https://cr.yp.to/proto/maildir.html "Using maildir format"
.Sh AUTHORS
.An Leah Neukirchen Aq Mt leah@vuxu.org
.Sh LICENSE
.Nm
is in the public domain.
.Pp
To the extent possible under law,
the creator of this work
has waived all copyright and related or
neighboring rights to this work.
.Pp
.Lk http://creativecommons.org/publicdomain/zero/1.0/
