.Dd July 22, 2016
.Dt MMIME 1
.Os
.Sh NAME
.Nm mmime
.Nd encode MIME mails
.Sh SYNOPSIS
.Nm
.Op Fl c | Fl r
<
.Ar message
.Sh DESCRIPTION
.Nm
encodes the standard input into a MIME message.
.Pp
.Nm
generates a
.Sq Li multipart/mixed
mail from standard input,
extending, wrapping, and encoding the header as neccessary,
and replacing body lines looking like
.Pp
.D1 Li # Ns Ar type Pa filename
.Pp
with a MIME part having Content-Type
.Ar type
consisting of the contents of
.Pa filename .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
Check mode: don't output anything,
exit with status 1 if MIME-encoding the message is required,
or with status 0 else.
.It Fl r
Raw mode: don't expand MIME parts in the body, generate a
.Sq Li text/plain
message.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Rs
.%A N. Freed
.%A N. Borenstein
.%D November 1996
.%R RFC 2045
.%T Multipurpose Internet Mail Extensions (MIME) Part One: Format of Internet Message Bodies
.Re
.Rs
.%A N. Freed
.%A N. Borenstein
.%D November 1996
.%R RFC 2046
.%T Multipurpose Internet Mail Extensions (MIME) Part Two: Media Types
.Re
.Rs
.%A K. Moore
.%D November 1996
.%R RFC 2047
.%T MIME (Multipurpose Internet Mail Extensions) Part Three: Message Header Extensions for Non-ASCII Text
.Re
.Rs
.%A P. Resnick (ed.)
.%B Internet Message Format
.%R RFC 5322
.%D October 2008
.Re
.Sh AUTHORS
.An Leah Neukirchen Aq Mt leah@vuxu.org
.Sh LICENSE
.Nm
is in the public domain.
.Pp
To the extent possible under law,
the creator of this work
has waived all copyright and related or
neighboring rights to this work.
.Pp
.Lk http://creativecommons.org/publicdomain/zero/1.0/
