.Dd July 22, 2016
.Dt MMIME 1
.Os
.Sh NAME
.Nm mmime
.Nd create MIME messages
.Sh SYNOPSIS
.Nm
.Op Fl c | Fl r
.Op Fl t Ar content-type
<
.Ar message
.Sh DESCRIPTION
.Nm
generates a
.Sq Li multipart/mixed
message from the standard input,
extending, wrapping, and encoding the header as necessary,
and replacing lines in the message body of the form
.Pp
.D1 Li # Ns Ar content Ns Li / Ns Ar type Ns Oo Ns Li # Ns Ar content-disposition Oc Pa path Ns Oo Li > Ns Ar filename Oc
.Pp
with a MIME part having Content-Type
.Ar content/type ,
consisting of the contents of the file found at
.Pa path .
.Ar content-disposition
is optional and defaults to
.Sq attachment .
.Ar filename
is optional and defaults to the basename of
.Ar path .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
Check mode: don't output anything,
exit with status 1 if MIME-encoding the message is required,
or else exit with status 0.
.It Fl r
Raw mode: don't expand MIME parts in the body, generate a
.Sq Li text/plain
message.
.It Fl t Ar content-type
Override Content-Type for the toplevel part.
Defaults to
.Sq Li multipart/mixed .
.El
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev MBLAZE_RELAXED_MIME
If set,
.Nm Fl c
will relax the body line length check and only consider bodies with lines
longer than 998 characters need to be MIME formatted.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr makemime 1 ,
.Xr mhbuild 1
.Rs
.%A N. Freed
.%A N. Borenstein
.%D November 1996
.%R RFC 2045
.%T Multipurpose Internet Mail Extensions (MIME) Part One: Format of Internet Message Bodies
.Re
.Rs
.%A N. Freed
.%A N. Borenstein
.%D November 1996
.%R RFC 2046
.%T Multipurpose Internet Mail Extensions (MIME) Part Two: Media Types
.Re
.Rs
.%A K. Moore
.%D November 1996
.%R RFC 2047
.%T MIME (Multipurpose Internet Mail Extensions) Part Three: Message Header Extensions for Non-ASCII Text
.Re
.Rs
.%A N. Freed
.%A K. Moore
.%D November 1997
.%R RFC 2231
.%T MIME Parameter Value and Encoded Word Extensions: Character Sets, Languages, and Continuations
.Re
.Rs
.%A P. Resnick (ed.)
.%D October 2008
.%R RFC 5322
.%T Internet Message Format
.Re
.Sh AUTHORS
.An Leah Neukirchen Aq Mt leah@vuxu.org
.Sh LICENSE
.Nm
is in the public domain.
.Pp
To the extent possible under law,
the creator of this work
has waived all copyright and related or
neighboring rights to this work.
.Pp
.Lk http://creativecommons.org/publicdomain/zero/1.0/
