.Dd July 22, 2016
.Dt MSEQ 1
.Os
.Sh NAME
.Nm mseq
.Nd manipulate mail sequence
.Sh SYNOPSIS
.Nm
.Op Fl fnr
.Ar msgs\ ...
.Nm
.Fl S
.Op Fl fr
<
.Ar sequence
.Nm
.Fl A
.Op Fl fr
<
.Ar sequence
.Nm
.Fl C Ar msg
.Sh DESCRIPTION
.Nm
prints, fixes and sets messages in the mail sequence.
See
.Xr mmsg 7
for the message argument syntax.
.Pp
If no
.Ar msgs
are passed and
.Nm
is used interactively,
.Nm
prints all messages in the sequence.
.Pp
.Pp
With
.Fl S
or
.Fl A ,
.Nm
will replace (resp. append) the default sequence.
If standard output is not a terminal, the new sequence is also printed.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl f
Fix non-existing filenames by searching for a message with the same
Maildir id (but different flags).
.It Fl n
Print the sequence numbers of the
.Ar msgs .
.It Fl r
Remove leading indentation from the file names.
.It Fl S
Set the mail sequence to the file names passed on standard input.
.It Fl A
Like
.Fl S ,
but append to the mail sequence instead of replacing it.
.It Fl C Ar msg
Set the current message to
.Ar msg
and exit.
.El
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev MAILSEQ
File were the sequence is stored.
(Default:
.Pa ~/.santoku/seq )
.It Ev MAILCUR
Symbolic link referring to the current message.
(Default:
.Pa ~/.santoku/cur )
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr mmsg 7
.Sh AUTHORS
.An Christian Neukirchen Aq Mt chneukirchen@gmail.com
.Sh LICENSE
.Nm
is in the public domain.
.Pp
To the extent possible under law,
the creator of this work
has waived all copyright and related or
neighboring rights to this work.
.Pp
.Lk http://creativecommons.org/publicdomain/zero/1.0/
