.Dd July 22, 2016
.Dt MSETSEQ 1
.Os
.Sh NAME
.Nm msetseq
.Nd set mail sequence
.Sh SYNOPSIS
.Nm
.Op Fl a
.Sh DESCRIPTION
.Nm
sets the mail sequence to the file names passed on standard input.
.Pp
When used in a pipe,
.Nm
will also output the full sequence, so it can be used in a pipe.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl a
Append to the mail sequence instead of replacing it.
.El
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev MAILMAP
File were the sequence is stored.
(Default:
.Pa ~/.santoku/map )
.El
.Sh EXIT STATUS
.Ex -std
.Sh AUTHORS
.An Christian Neukirchen Aq Mt chneukirchen@gmail.com
.Sh LICENSE
.Nm
is in the public domain.
.Pp
To the extent possible under law,
the creator of this work
has waived all copyright and related or
neighboring rights to this work.
.Pp
.Lk http://creativecommons.org/publicdomain/zero/1.0/
