#!/bin/sh
# mpeek - wrapper around mscan with a different seq

if [ -z "$XDG_CONFIG_HOME" ]; then
	MAILSEQ="$XDG_CONFIG_HOME/mblaze"
else
	MAILSEQ="$HOME/.config/mblaze"
fi

[ ! -d "$MAILSEQ" ] && MAILSEQ="$HOME/.mblaze"

export MAILSEQ=$MAILSEQ/peek.seq

if [ -t 0 ]; then
	mseq "$@"
else
	mseq -S | mscan "$@"
fi

