#!/bin/sh
# mless [MSG] - less(1)-wrapper around mshow

colorscan() {
awk '
function co(n, c) { e = ENVIRON["MCOLOR_" n]; return e ? e : c }
function fg(c, s) { return sprintf("\033[38;5;%03dm%s\033[0m", c, s) }
function so(s) { return sprintf("\033[1m%s\033[0m", s) }
/^>/ { print so(fg(co("CUR",119), $0)); next }
/^ *\\_/ { print fg(co("MISS",242), $0); next }
{ print }'
}

if [ -n "${NO_COLOR+set}" ]; then
	colorscan() { cat -; }
fi

if [ "$1" = --filter ]; then
	if [ "$2" = //scan ]; then
		mscan : 2>/dev/null | colorscan
		exit $?
	fi

	mseq -C "$2"

	total=$(mscan -n -- -1)
	case $2 in
		1)              mscan .-0:.+5 ;;
		2)              mscan .-1:.+4 ;;
		$((total - 2))) mscan .-3:.+2 ;;
		$((total - 1))) mscan .-4:.+1 ;;
		$total)         mscan .-5:.+0 ;;
		*)              mscan .-2:.+3 ;;
	esac 2>/dev/null | colorscan
	echo

	if ! [ -f "$(mseq -r "$2")" ]; then
		mseq "$2"
		exit
	fi

	if [ $MLESS_RAW -eq 0 ]; then
		if [ $MLESS_HTML -eq 1 ]; then
			mshow -A text/html "$2"
		else
			mshow "$2"
		fi | mcolor
	else
		mseq -r "$2"
		echo
		cat "$(mseq -r "$2")"
	fi
	exit $?
fi

if [ "$#" -eq 0 ] && ! [ -t 0 ]; then
	mseq -S >/dev/null
	set -- :
fi

if ! [ -t 1 ]; then
	exec mseq :
fi

[ "$#" -eq 1 ] && set -- ${1:-.}

if [ "$#" -ge 1 ]; then
	mseq -C "$1"
fi

nl="
"
export MLESS_RAW=0
export MLESS_HTML=0
if [ -f "$MBLAZE/mlesskey" ]; then
	export LESSKEYIN="$MBLAZE/mlesskey"
elif [ -f "$HOME/.mblaze/mlesskey" ]; then
	export LESSKEYIN="$HOME/.mblaze/mlesskey"
elif [ -f "$HOME/.mlesskey" ]; then
	export LESSKEYIN="$HOME/.mlesskey"
elif [ -f "$MBLAZE/mless" ]; then
	export LESSKEY="$MBLAZE/mless"
elif [ -f "$HOME/.mblaze/mless" ]; then
	export LESSKEY="$HOME/.mblaze/mless"
elif [ -f "$HOME/.mless" ]; then
	export LESSKEY="$HOME/.mless"
fi
while :; do
	LESSOPEN="|$0 --filter %s" \
		less -Ps"mless %f?m (message %i of %m).." -R \
			"+:e $(mscan -n .)$nl" //scan $(mscan -n :)
	_c="$?"
	case "$_c" in
	0|1) exit $?;;
	36) # $ goto end
		mseq -C '$' 2>/dev/null
		;;
	78) # N go to next unseen message
		nu=$(magrep -v -m1 :S .:) && mseq -C "$nu"
		;;
	118) # v rdrview?
		mshow -F -O . "$(mshow -t | awk '/text\/html/{print substr($1,1,length($1)-1)}')" | \
			rdrview -H | tidy | webdump -r8 -w"$_PREFWIDTH" | less
		;;
	119) # w open as pdf
		mshow -t | sed -n '1d;s/^  \([[:digit:]]\+\).*$/mshow -O \1/p' | sh | \
			tidy | hpdf 2>/dev/null
		;;
	68) # D delete
		mscan . | cat
		{
			rm -i "$(mseq .)" && mseq -C .- && mseq -f | mseq -S
		}
		;;
	82) # R
		mrep
		;;
	107) # k next thread
		mseq -C "$(mseq .+1: | sed -n '/^[^ <]/{p;q;}')"
		;;
	70) # F mark flaged
		if printf '%s' "$(mseq)" | grep -q ',\w*F\w*$'; then
			mflag -f .
		else
			mflag -F .
		fi
		mseq -f | mseq -S
		;;
	114) # r mark read
		mflag -S .
		mseq -f : | mseq -S
		mseq -C +
		;;
	111) # o view attachment
		names="$(mshow -t . | sed '/name=/!d')"
		if [ ! "$names" = "" ]; then
			printf %s "$names" | dmenu | sed 's/^\s\+\([[:digit:]]\+\):\s\([a-z\/]\+\).\+name="\(.\+\)"/mshow -O . \1 > \/tmp\/"\3" \&\& xdg-open \/tmp\/"\3"/' | sh >/dev/null 2>&1 &
		else
			notify-send "mless" "No attachments" &
		fi
		;;
	115) # s save attachment
		names="$(mshow -t . | sed '/name=/!d')"
		if [ ! "$names" = "" ]; then
			_dir="$(find Documents Downloads Pictures Sync -maxdepth 2 -type d -printf "%d %p\n"|sort -n | cut -d' ' -f2 | dmenu)"
			if [ ! "$_dir" = "" ]; then
				printf %s "$names" | dmenu | sed 's/^\s\+\([[:digit:]]\+\):\s\([a-z\/]\+\).\+name="\(.\+\)"/mshow -O . \1 > \$HOME\/'"$_dir"'\/"\3"/' | sh >/dev/null 2>&1 && notify-send "mless" "Saved to $_dir" &
			fi
		else
			notify-send "mless" "No attachments to save" &
		fi
		;;
	38) # & extract URLs
		_url="$(munsub)"
		if [ "$_url" != "" ]; then
			handle-url "$_url"
		else
			clear
			printf '%s' "No unsubscribe URLs found"
			# wait for char press
			o=$(stty -g); stty raw -echo ; head -c 1 ; stty "$o"
		fi
		;;
	98) # b extract URLs
		_url="$(mshow -N -h ''| extract_url -l -c "$XDG_CONFIG_HOME"/urlview/config 2>&- | fzf)"
		[ "$_url" != "" ] && handle-url "$_url"
		;;
	84) # T toggle raw mode
		MLESS_RAW=$((1-MLESS_RAW))
		;;
	72) # H toggle HTML mode
		MLESS_HTML=$((1-MLESS_HTML))
		;;
	94) # ^ goto parent
		mseq -C '.^' 2>/dev/null
		;;
	esac
done
